{{- $workspaceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $authServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $subscriptionUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $pennywiseUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $informationUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $describeSchedulerUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $onboardServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $policyServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $inventoryServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $complianceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $metadataServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $migratorServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $reporterServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $postgresExporterUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $steampipeUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $alertingServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $integrationServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $assistantServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $dexServiceUserPassword  := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
{{- if $secret }}
{{- $workspaceServiceUserPassword = index $secret.data "workspaceServiceUserPassword" | default $workspaceServiceUserPassword }}
{{- $authServiceUserPassword = index $secret.data "authServiceUserPassword" | default $authServiceUserPassword }}
{{- $subscriptionUserPassword = index $secret.data "subscriptionUserPassword" | default $subscriptionUserPassword}}
{{- $pennywiseUserPassword = index $secret.data "pennywiseUserPassword" | default $pennywiseUserPassword }}
{{- $informationUserPassword = index $secret.data "informationUserPassword" | default $informationUserPassword }}
{{- $describeSchedulerUserPassword = index $secret.data "describeSchedulerUserPassword" | default $describeSchedulerUserPassword }}
{{- $onboardServiceUserPassword = index $secret.data "onboardServiceUserPassword" | default $onboardServiceUserPassword }}
{{- $policyServiceUserPassword = index $secret.data "policyServiceUserPassword" | default $policyServiceUserPassword }}
{{- $inventoryServiceUserPassword = index $secret.data "inventoryServiceUserPassword" | default $inventoryServiceUserPassword }}
{{- $complianceServiceUserPassword = index $secret.data "complianceServiceUserPassword" | default $complianceServiceUserPassword }}
{{- $metadataServiceUserPassword = index $secret.data "metadataServiceUserPassword" | default $metadataServiceUserPassword }}
{{- $migratorServiceUserPassword = index $secret.data "migratorServiceUserPassword" | default $migratorServiceUserPassword }}
{{- $reporterServiceUserPassword = index $secret.data "reporterServiceUserPassword" | default $reporterServiceUserPassword }}
{{- $postgresExporterUserPassword = index $secret.data "postgresExporterUserPassword" | default $postgresExporterUserPassword }}
{{- $steampipeUserPassword = index $secret.data "steampipeUserPassword" | default $steampipeUserPassword }}
{{- $alertingServiceUserPassword = index $secret.data "alertingServiceUserPassword" | default $alertingServiceUserPassword}}
{{- $integrationServiceUserPassword = index $secret.data "integrationServiceUserPassword" | default $integrationServiceUserPassword}}
{{- $assistantServiceUserPassword = index $secret.data "assistantServiceUserPassword" | default $assistantServiceUserPassword}}
{{- $dexServiceUserPassword = index $secret.data "dexServiceUserPassword" | default $dexServiceUserPassword}}
{{- end -}}

{{- $issuer := .Values.dex.config.issuer }}
{{- if not $issuer -}}
{{- $issuer = printf "http://%s-dex.%s.svc.cluster.local:5556/dex" .Release.Name .Release.Namespace }}
{{- end }}
{{- $postgres := dict "host" (include "postgres.endpoint" .) "port" (include "postgres.port" . | int) "database" "dex" "user" "dex_service" "password" ($dexServiceUserPassword | replace "\"" "" | b64dec) "ssl" (dict "mode" (include "postgres.sslMode" .)) }}
{{- $config := include "dex.config" . | fromYaml | merge (dict "issuer" $issuer) | merge (dict "storage" (dict "config" $postgres))}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  workspaceServiceUserPassword: {{ $workspaceServiceUserPassword }}
  pennywiseUserPassword: {{ $pennywiseUserPassword }}
  authServiceUserPassword: {{ $authServiceUserPassword }}
  subscriptionUserPassword: {{ $subscriptionUserPassword }}
  informationUserPassword: {{ $informationUserPassword }}
  describeSchedulerUserPassword: {{ $describeSchedulerUserPassword }}
  onboardServiceUserPassword: {{ $onboardServiceUserPassword }}
  policyServiceUserPassword: {{ $policyServiceUserPassword }}
  inventoryServiceUserPassword: {{ $inventoryServiceUserPassword }}
  complianceServiceUserPassword: {{ $complianceServiceUserPassword }}
  metadataServiceUserPassword: {{ $metadataServiceUserPassword }}
  migratorServiceUserPassword: {{ $migratorServiceUserPassword }}
  reporterServiceUserPassword: {{ $reporterServiceUserPassword }}
  postgresExporterUserPassword: {{ $postgresExporterUserPassword }}
  steampipeUserPassword: {{ $steampipeUserPassword }}
  alertingServiceUserPassword: {{ $alertingServiceUserPassword }}
  assistantServiceUserPassword: {{ $assistantServiceUserPassword }}
  dexServiceUserPassword: {{ $dexServiceUserPassword }}
  integrationServiceUserPassword: {{ $integrationServiceUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dex
type: Opaque
data:
  config.yaml: {{ $config | toYaml | b64enc | quote }}
